### ISSUE TITLE
Ajouter le SSL / HTTPS

### ISSUE THREAD

**Issue by aHenryJard** [DuchessFrance/DuchessFrance.github.io#101]
- Prendre un certificat, par default on a pensé à let's encrypt
- configurer les github pages pour l'appliquer
![image](https://user-images.githubusercontent.com/3634942/213425332-ba1bd324-178a-4b0c-be05-da41fe375bd6.png)

**Comment by Pompette** [comment]
Hello,

Il faut avoir accès aux paramètres du repo pour configurer l'option SSL.
Il faut cocher une checkbox pour activer la redirection [cf](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https)

**Comment by aHenryJard** [comment]
bon en fait c'était super simple !
