### ISSUE TITLE
Faire marcher la pagination sur les posts de blog

### ISSUE THREAD

**Issue by aHenryJard** [DuchessFrance/DuchessFrance.github.io#11]
Y a un début de configuration qui visiblement ne marche pas.

**Comment by alauregaillard** [comment]
D'après les logs cela viendrait du fait qu'on ait pas de fichier index.html. Sur internet je trouve le même constat : 
https://stackoverflow.com/questions/57659321/how-to-paginate-in-jekyll

Je vois deux options :
- soit on inclut la page home.html dans le fichier index.md et on le renomme en index.html
- soit on renomme le home.html et on ajoute paginate_path: "/blog/page:num/" dans le fichier de conf.
Vous avez un avis ou une bonne pratique ?
