### ISSUE TITLE
Agrandir un peu la zone centrale

### ISSUE THREAD

**Issue by aHenryJard** [DuchessFrance/DuchessFrance.github.io#19]
Sur le site existant https://www.duchess-france.org/ la zone centrale sur laquelle sont affichés les posts est un peu plus large sur un écran d'ordinateur.

A voir s'il est possible de se rapprocher de la même taille, et vérifier que ça marche toujours correctement sur écran de téléphone.

**Comment by bbourgois** [comment]
est-ce qu'on va remettre la colonne avec  : sponsor, nous y serons ?

**Comment by aHenryJard** [comment]
> est-ce qu'on va remettre la colonne avec : sponsor, nous y serons ?

oui je suis d'accord, faut qu'on discute ça, je l'avais écrit dans cette autre issue https://github.com/DuchessFrance/DuchessFrance.github.io/issues/7 mais effectivement les 2 sont liées.

**Comment by aHenryJard** [comment]
Je ferme cette issue vu que la zone centrale est un peu plus grande, on continue sur celle des sponsors pour le reste.
