### ISSUE TITLE
Finir le pied de page

### ISSUE THREAD

**Issue by aHenryJard** [DuchessFrance/DuchessFrance.github.io#20]
Les liens et le texte ont été ajouté rapidement. Il faudrait faire le tour des média duchess a afficher, et voir quel texte on met en bas aussi.
![footer](https://user-images.githubusercontent.com/3634942/158113778-3b33d672-13c5-4526-a18c-3601a58b4239.png)

**Comment by bbourgois** [comment]
Comment on se décide pour cette issue. vous voulez monter un point ?

**Comment by aHenryJard** [comment]
Extrait du CR de la core team => 

> mentions légales (rajouter une issue pour créer la page), twitter, github, description, pas d’email en clair (pour les  bots).
