### ISSUE TITLE
Trouver et ajouter la photo manquante sur la page de la core-team Duchess

### ISSUE THREAD

**Issue by alauregaillard** [DuchessFrance/DuchessFrance.github.io#23]
Trouver et ajouter la photo manquante sur la page de la core-team Duchess

**Comment by bbourgois** [comment]
j'ai envoyé un message à @scraly pour récup une photo.

**Comment by scraly** [comment]
Coucou, pour ma photo vous pouvez prendre celle là :
https://pbs.twimg.com/profile_images/1412503128977645575/Z55hCP1c_400x400.jpg

merciiii

**Comment by aHenryJard** [comment]
C'est envoyé, merci pour la contribution à toutes !
