### ISSUE TITLE
Trouver une solution pour pouvoir contribuer au blog sans avoir à tout installer

### ISSUE THREAD

**Issue by bbourgois** [DuchessFrance/DuchessFrance.github.io#27]
Bonjour

L'installation de l'env complet est longue (en particulier sur windows) : 
- make
- gcc
- ruby
- jekyll
De plus, on peut rencontrer des difficultés (dépendances incompatible ...). En particulier, si on est pas admin de sa machine, ca devient impossible de faire l'install simplement.
C'est dommage et peut être décourageant de passer autant de temps sur l'install pour juste publier un post.

-> créer une image docker ?

**Comment by aHenryJard** [comment]
Super merci, j'avais essayé rapidement mais je m'étais heurtée à des pb de droits sur fichier, je peux beta tester si vous voulez.

**Comment by Pompette** [comment]
@aHenryJard je veux bien que tu tests la PR qui est en draft si tu as le temps, je l'ai mis en draft justement car je n'ai testé que sous Mac et je ne suis pas sur que ce soit ok sur les autres système.
Pour tester il faut que tu sois dans le dossier docs de la branch, et que tu fasses `docker-compose up`

**Comment by scraly** [comment]
Pour faciliter cet aspect comment contribuer, sans avoir a tout installer, vous connaissez GitPod ?

Si la deadline n'est pas trop court,e je pourrais regarder si cela vous dit.
Comme cela, dans le readme on mettra un bouton "open to gipod" par exemple, cela ouvrira un VSCode dans la navigateur, au demarrage du workspace cela créera l'environnement et pouf il  n'y aura plus qu'a contribuer :)

**Comment by scraly** [comment]
GitPod propose 50 heures gratuite d'utilisation par mois, et pour un projet open source on peut demander unlimited.

**Comment by aHenryJard** [comment]
@scraly la dernière fois que j'ai essayé gitpod je pense que je suis tombée juste au moment où ça marchait pas. 100% motivée pour l'essayer et zéro install sur le poste.

**Comment by Pompette** [comment]
ça a l'air trop cool GitPod 🔥

**Comment by scraly** [comment]
J'ai créé une PR avec l'intégration avec GitPod
