### ISSUE TITLE
Migration du nom de domaine

### ISSUE THREAD

**Issue by aHenryJard** [DuchessFrance/DuchessFrance.github.io#37]
A faire par une des membres de la core team. Le nom de domaine actuel a besoin d'être migré avant l'ouverture du site.

**Comment by scraly** [comment]
J'ai envoyé un mail a Claude cette semaine.
Si pas de news, je la relancerai semaine prochaine.

**Comment by bbourgois** [comment]
@scraly est-ce que tu as au un retour ?

**Comment by scraly** [comment]
non :'(

**Comment by aHenryJard** [comment]
On a le nom de domaine, il faut maintenant le configurer sur la github pages.

**Comment by aHenryJard** [comment]
fait sur duchess-france.fr pour l'instant.
