### ISSUE TITLE
Articles du blog, certains caractères ne sont pas correctement encodés

### ISSUE THREAD

**Issue by alauregaillard** [DuchessFrance/DuchessFrance.github.io#40]
Articles du blog, certains caractères ne sont pas correctement encodés.
Exemples en photo sur les titres
![image](https://user-images.githubusercontent.com/86982045/159125055-00cdd9fa-468c-4dae-9e50-e710e2d99a47.png)
![image](https://user-images.githubusercontent.com/86982045/159125094-977f1b62-5bf6-44d2-a050-f3a46cd264b6.png)

**Comment by aHenryJard** [comment]
Mergé
