### ISSUE TITLE
migrer la page presse https://www.duchess-france.org/presse/

### ISSUE THREAD

**Issue by cbm-fchabanois** [DuchessFrance/DuchessFrance.github.io#42]

**Comment by aHenryJard** [comment]
J'ai un doute sur cette page, vu la date des références... Y a pas de mise à jour depuis 4 ans, j'ai l'impression qu'on a pas trop la bande passante pour la maintenir.

**Comment by bbourgois** [comment]
je pense que ce n'est pas nécessaire de migrer cette page. -> à clôturer
