### ISSUE TITLE
migrer la page Femmes speaker

### ISSUE THREAD

**Issue by cbm-fchabanois** [DuchessFrance/DuchessFrance.github.io#44]
https://www.duchess-france.org/des-oratrices/

**Comment by aHenryJard** [comment]
Ça serait bien d'en rajouter un peu au passage. Par exemple en demandant dans le Slack aux femmes speaker de se faire connaître et les ajouter. C'est pas obligatoire pour traiter l'issue, juste une proposition d'amélioration.

**Comment by bbourgois** [comment]
Je pense que la page est pas du tout à jour. Peut-être commencer par rajouter les speakeuses des confs à venir (devoxx ...)

**Comment by aHenryJard** [comment]
Mergé
