### ISSUE TITLE
Ajouter le contenu de la page Contributrices dans A propos

### ISSUE THREAD

**Issue by cbm-fchabanois** [DuchessFrance/DuchessFrance.github.io#45]
afin d'ouvrir la porte aux articles invité·es ? ou pas nécessaire vu le format jekyll ?

**Comment by aHenryJard** [comment]
C'est plutôt le côté open Source qui me paraît en doublon. Sinon on peut juste faire un lien quelque part sur le site vers CONTRIBUTING.md

**Comment by aHenryJard** [comment]
Je viens de relire le titre. 💯 D'accord que la partie contribution peut aller dans la page "a propos"

**Comment by aHenryJard** [comment]
ca m'a l'air fait, je clos du coup.
