### ISSUE TITLE
Migrer les rôles modèles 

### ISSUE THREAD

**Issue by aHenryJard** [DuchessFrance/DuchessFrance.github.io#46]
Pas facile étant donné que la page d'accueil actuelle est cassée. Il faudrait voir si on peut quand même récupérer les articles d'un export WordPress.

**Comment by bbourgois** [comment]
sauf erreur, tous les post concernant les roles modèles ont la catégorie : les-portraits

**Comment by vvenance** [comment]
est ce que c'est toujours ouvert ?

**Comment by aHenryJard** [comment]
non c'est fait dans la partie post, à voir si on veut les remettre en avant quelque part.
