### ISSUE TITLE
Faire la migration de la page "Elles font Duchess"

### ISSUE THREAD

**Issue by aHenryJard** [DuchessFrance/DuchessFrance.github.io#6]
Migrer le contenu de la page "La team" dans Elles fotn duchess https://www.duchess-france.org/la-team-duchess-france/

vers https://github.com/DuchessFrance/DuchessFrance.github.io/blob/main/docs/core-team.md

Note: la page "Elles font Duchess > Contributrice" est quasiment vide, pas besoin de migration. Eventuellement le texte peut se glisser dans une des pages du nouveau site.

**Comment by alauregaillard** [comment]
Bonjour @aHenryJard tu peux me l'assigner s'il te plait ? Merci.

**Comment by aHenryJard** [comment]
Mergé et déployé !
