### ISSUE TITLE
Faire la migration de la partie sponsors

### ISSUE THREAD

**Issue by aHenryJard** [DuchessFrance/DuchessFrance.github.io#7]
Les sponsors sont sur la page d'accueil de https://www.duchess-france.org/ à droite.

- A voir et discuter si on les laisse sur la page d'accueil ou si on les met sur une page dédié
- migrer les sponsors et faire le tri sur ceux qui ne sont plus d'actualité

**Comment by aHenryJard** [comment]
Faut une descision de la Core Team Duchess sur l'emplacement des sponsors, donc j'ajoute le label core-team tant que c'est pas décidé.

**Comment by aHenryJard** [comment]
Les sponsors doivent être sur la page d'accueil, par ordre du plus récent au plus ancien et potentiellement classés par années, dans l'idée un truc comme ça =>
![sponsors](https://user-images.githubusercontent.com/3634942/164894453-42f1203c-a324-410f-86a5-46f28c2c3831.png)

**Comment by Pompette** [comment]
Ou peut-on trouver la liste des sponsors ? @aHenryJard 
Sur la v1 du site je ne vois que codeworks comme sponsor

**Comment by aHenryJard** [comment]
Penser à ajouter KCD https://www.kcdfrance.fr/

**Comment by aHenryJard** [comment]
pour cette année en tout cas il y a Dataiku (anniversaire) et KCD
