### ISSUE TITLE
Rattrapage https://www.duchess-france.org/les-details-du-sondage-devoile-a-lanniversaire-duchess-chez-dataiku/

### ISSUE THREAD

**Issue by aHenryJard** [DuchessFrance/DuchessFrance.github.io#78]
cf https://www.duchess-france.org/les-details-du-sondage-devoile-a-lanniversaire-duchess-chez-dataiku/

**Comment by vvenance** [comment]
C'est encore ouvert ou on peut close l'issue ?

**Comment by aHenryJard** [comment]
Livré
