### ISSUE TITLE
Mettre une jolie favicon :)

### ISSUE THREAD

**Issue by aHenryJard** [DuchessFrance/DuchessFrance.github.io#9]
Celle qui est actuellement dans git est pas du tout adaptée, il faut la changer ^^

https://github.com/DuchessFrance/DuchessFrance.github.io/blob/main/docs/favicon.ico

**Comment by codexarama** [comment]
Je propose ce visuel pour remplacer la favicon actuelle :

![favicon_duchess](https://user-images.githubusercontent.com/75674263/158160901-a2c088c3-36e7-456c-a2c8-22f6bb2f1592.svg)

**Comment by aHenryJard** [comment]
Ok pour moi.
